services:
  postgres:
    container_name: postgres
    image: postgres:16.1
    environment:
      - POSTGRES_USER=postgres
      - POSTGRES_PASSWORD=postgres
      - POSTGRES_DB=chat-next
    ports:
      - 5432:5432
    volumes:
      - ./var/postgres:/var/lib/postgresql/data/